/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgLookupPenerimaan.java
 *
 * Created on Apr 11, 2009, 3:55:01 PM
 */

package retail;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ustadho
 */
public class DlgLookupPenerimaan extends javax.swing.JDialog {
    Connection conn;
    retail.main.ListRsbm lst=new retail.main.ListRsbm();
    private boolean isLookup;
    DefaultTableModel hModel, dModel;

    /** Creates new form DlgLookupPenerimaan */
    public DlgLookupPenerimaan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        hModel=(DefaultTableModel)tblGR.getModel();
        hModel.setNumRows(0);
        tblGR.setModel(hModel);

        dModel=(DefaultTableModel)tblDetail.getModel();
        dModel.setNumRows(0);
        tblDetail.setModel(dModel);

    }

    public void setIsLookup(boolean b){
        this.isLookup=b;
    }

    public void setConn(Connection con){
        this.conn=con;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblGR = new org.jdesktop.swingx.JXTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jXTitledPanel1 = new org.jdesktop.swingx.JXTitledPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetail = new org.jdesktop.swingx.JXTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtKodeSupp = new javax.swing.JTextField();
        lblNamaSupp = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pembelian / Penerimaan Barang");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblGR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No. Trans", "Tanggal", "Supplier"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGR.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tblGR);
        tblGR.getColumnModel().getColumn(0).setResizable(false);
        tblGR.getColumnModel().getColumn(0).setPreferredWidth(100);
        tblGR.getColumnModel().getColumn(1).setResizable(false);
        tblGR.getColumnModel().getColumn(2).setResizable(false);
        tblGR.getColumnModel().getColumn(2).setPreferredWidth(230);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Pilih");

        jXTitledPanel1.setTitle("Detail Barang");
        jXTitledPanel1.getContentContainer().setLayout(new javax.swing.BoxLayout(jXTitledPanel1.getContentContainer(), javax.swing.BoxLayout.LINE_AXIS));

        tblDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode", "Item", "Qty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDetail);
        tblDetail.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblDetail.getColumnModel().getColumn(2).setPreferredWidth(70);

        jXTitledPanel1.getContentContainer().add(jScrollPane2);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("S/D");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 40, 20));
        jPanel1.add(jXDatePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 140, -1));
        jPanel1.add(jXDatePicker2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 130, -1));

        jLabel2.setText("Dari :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 20));

        jLabel17.setText("Supplier"); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 60, 21));

        txtKodeSupp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtKodeSupp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKodeSuppFocusLost(evt);
            }
        });
        txtKodeSupp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKodeSuppKeyReleased(evt);
            }
        });
        jPanel1.add(txtKodeSupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 80, 21));

        lblNamaSupp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblNamaSupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 420, 21));

        jButton3.setText("Load");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 50, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jXTitledPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jXTitledPanel1, 0, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-799)/2, (screenSize.height-469)/2, 799, 469);
    }// </editor-fold>//GEN-END:initComponents

    private void txtKodeSuppFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKodeSuppFocusLost
        //        if(!lst.isVisible() && !txtNoAnggota.getText().equalsIgnoreCase("") && isNew)
        //            txtPinjamanKe.setText(numFmt.format(getPinjamanKe()));
}//GEN-LAST:event_txtKodeSuppFocusLost

    private void txtKodeSuppKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeSuppKeyReleased
        try {
            String sCari = txtKodeSupp.getText();
            switch (evt.getKeyCode()) {
                case java.awt.event.KeyEvent.VK_ENTER: {
                    if (lst.isVisible()) {
                        Object[] obj = lst.getOResult();
                        if (obj.length > 0) {
                            txtKodeSupp.setText(obj[0].toString());
                            lst.udfSelected();
                            lst.setVisible(false);
                        }
                    }
                    break;
                }
                case java.awt.event.KeyEvent.VK_DELETE: {
                    lst.setFocusable(true);
                    lst.requestFocus();

                    break;
                }
                case java.awt.event.KeyEvent.VK_ESCAPE: {
                    lst.setVisible(false);
                    txtKodeSupp.setText("");
                    lblNamaSupp.setText("");
                    break;
                }
                case java.awt.event.KeyEvent.VK_DOWN: {
                    if (lst.isVisible()) {
                        lst.setFocusableWindowState(true);
                        lst.setVisible(true);
                        lst.requestFocus();
                    }
                    break;
                }
                default: {
                    if (!evt.getKeyText(evt.getKeyCode()).equalsIgnoreCase("Up") || !evt.getKeyText(evt.getKeyCode()).equalsIgnoreCase("F2")) {
                        String sQry = "select kode_supp as Kode, coalesce(nama_supp,'') as Supplier, " +
                                "coalesce(alamat_1,'')||' '||coalesce(nama_kota,'') as alamat  " +
                                "from r_supplier s " +
                                "left join m_kota k on s.kota=k.kode_kota " +
                                "where (kode_supp||coalesce(nama_supp,'')) " +
                                "iLike '%" + txtKodeSupp.getText() + "%' order by coalesce(nama_supp,'') ";

                        //System.out.println(sQry);
                        lst.setSQuery(sQry);

                        lst.setBounds(this.txtKodeSupp.getLocationOnScreen().x,
                                this.txtKodeSupp.getLocationOnScreen().y + txtKodeSupp.getHeight(),
                                txtKodeSupp.getWidth() + lblNamaSupp.getWidth()+120,
                                (lst.getIRowCount()>10? 12*lst.getRowHeight(): (lst.getIRowCount()+3)*lst.getRowHeight()));


                        lst.setFocusableWindowState(false);
                        lst.setTxtCari(txtKodeSupp);
                        lst.setCompDes(new javax.swing.JLabel[]{lblNamaSupp});
                        lst.setColWidth(0, txtKodeSupp.getWidth());
                        lst.setColWidth(1, lblNamaSupp.getWidth()-10);

                        if (lst.getIRowCount() > 0) {
                            lst.setVisible(true);
                            requestFocusInWindow();
                            txtKodeSupp.requestFocus();
                        } else {
                            lst.setVisible(false);
                            txtKodeSupp.setText("");
                            lblNamaSupp.setText("");
                            txtKodeSupp.requestFocus();
                        }
                    }
                    break;
                }
            }
        } catch (SQLException se) {
            System.out.println(se.getMessage());
        }
}//GEN-LAST:event_txtKodeSuppKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lst.setConn(this.conn);
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        lst.setVisible(false);
    }//GEN-LAST:event_formWindowClosed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        udfLoadPenerimaan();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgLookupPenerimaan dialog = new DlgLookupPenerimaan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel1;
    private javax.swing.JLabel lblNamaSupp;
    private org.jdesktop.swingx.JXTable tblDetail;
    private org.jdesktop.swingx.JXTable tblGR;
    private javax.swing.JTextField txtKodeSupp;
    // End of variables declaration//GEN-END:variables

    private void udfLoadPenerimaan() {
        try{
             ResultSet rs=conn.createStatement().executeQuery("select purchase_no, tanggal, " +
                     "coalesce(nama_supp,'') as supplier " +
                     "from r_purchase p inner join r_supplier s on s.kode_supp=p.kode_supp " +
                     "where to_Char(tanggal, 'yyyy-MM-dd')>='"+new SimpleDateFormat("yyyy-MM-dd").format(jXDatePicker1.getDate())+"' " +
                     "and to_Char(tanggal, 'yyyy-MM-dd')<='"+new SimpleDateFormat("yyyy-MM-dd").format(jXDatePicker2.getDate())+"' " +
                     "and p.kode_supp like '"+txtKodeSupp.getText()+"%'");

             while(rs.next()){
                hModel.addRow(new Object[]{
                    rs.getString("purchase_no"),
                    rs.getDate("tanggal"),
                    rs.getString("supplier")
                });
             }
             
        }catch(SQLException se){
            JOptionPane.showMessageDialog(this, se.getMessage());
        }
    }

}
