/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmItemLocation.java
 *
 * Created on 03 Feb 11, 14:55:02
 */

package retail;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import retail.main.GeneralFunction;

/**
 *
 * @author cak-ust
 */
public class FrmItemLocation extends javax.swing.JInternalFrame {
    private Connection conn;
    private String sKodeBarang;
    private GeneralFunction fn=new GeneralFunction();
    private Object objForm;

    /** Creates new form FrmItemLocation */
    public FrmItemLocation() {
        initComponents();
    }

    public void setConn(Connection con){
        this.conn=con;
        fn.setConn(conn);
    }

    public void setItem(String sKode, String sNama){
        this.sKodeBarang=sKode;
        setTitle(getTitle()+" - "+sKode);
        lblNamaItem.setText(sNama);
    }

    private void udfInitForm(){
        try{
            ((DefaultTableModel)tblLokasi.getModel()).setNumRows(0);

            ResultSet rs=conn.createStatement().executeQuery("select i.kode_lokasi, coalesce(nama_lokasi,'') as nama_lokasi " +
                    "from r_item_lokasi i " +
                    "left join r_lokasi l on l.kode_lokasi=i.kode_lokasi " +
                    "where kode_item='"+sKodeBarang+"'");
            while(rs.next()){
                ((DefaultTableModel)tblLokasi.getModel()).addRow(new Object[]{
                    rs.getString("kode_lokasi"),
                    rs.getString("nama_lokasi")
                });
            }
            if(((DefaultTableModel)tblLokasi.getModel()).getRowCount()>0)
                tblLokasi.setRowSelectionInterval(0, 0);

            rs.close();

        }catch(SQLException se){
            JOptionPane.showMessageDialog(this, se.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLokasi = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        txtLokasi = new javax.swing.JTextField();
        lblLokasi = new javax.swing.JLabel();
        lblNamaItem = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Lokasi Barang");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblLokasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Lokasi", "Lokasi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLokasi.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblLokasi.setAutoscrolls(false);
        tblLokasi.setName("tblLokasi"); // NOI18N
        tblLokasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblLokasiKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblLokasi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 450, 170));

        btnSimpan.setText("Add");
        btnSimpan.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnSimpan.setName("btnSimpan"); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 48, 60, 22));

        txtLokasi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtLokasi.setName("txtLokasi"); // NOI18N
        txtLokasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLokasiKeyReleased(evt);
            }
        });
        getContentPane().add(txtLokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, 20));

        lblLokasi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblLokasi.setName("lblLokasi"); // NOI18N
        getContentPane().add(lblLokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 290, 20));

        lblNamaItem.setBackground(new java.awt.Color(204, 204, 204));
        lblNamaItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNamaItem.setText("Rokok");
        lblNamaItem.setName("lblNamaItem"); // NOI18N
        lblNamaItem.setOpaque(true);
        getContentPane().add(lblNamaItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLokasiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLokasiKeyReleased
        fn.lookup(evt, new Object[]{lblLokasi}, "select kode_lokasi, coalesce(nama_lokasi,'') as nama_lokasi from r_lokasi " +
                "where kode_lokasi||coalesce(nama_lokasi,'') ilike '%"+txtLokasi.getText()+"%'", txtLokasi.getWidth()+lblLokasi.getWidth()+18, 120);
        
    }//GEN-LAST:event_txtLokasiKeyReleased

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        udfInitForm();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        udfInsertLokasi();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosed

    private void tblLokasiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblLokasiKeyPressed
        int iRow=tblLokasi.getSelectedRow();
        if(iRow>=0){
            try{
                if(JOptionPane.showConfirmDialog(this, "Anda yakin untuk menghapus lokasi item ini?", "Hapus Lokasi", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
                    int i=conn.createStatement().executeUpdate("delete from r_item_lokasi where kode_item='"+sKodeBarang+"' and " +
                            "kode_lokasi='"+tblLokasi.getValueAt(iRow, 0).toString()+"'");

                    ((DefaultTableModel)tblLokasi.getModel()).removeRow(iRow);
                    if(objForm instanceof FrmSettingHargaJual)
                        ((FrmSettingHargaJual)objForm).udfFilter(sKodeBarang);
                }
            }catch(SQLException se){
                JOptionPane.showMessageDialog(this, se.getMessage());
            }
        }
    }//GEN-LAST:event_tblLokasiKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLokasi;
    private javax.swing.JLabel lblNamaItem;
    private javax.swing.JTable tblLokasi;
    private javax.swing.JTextField txtLokasi;
    // End of variables declaration//GEN-END:variables

    void setObjForm(Object aThis) {
        this.objForm=aThis;
    }

    private void udfInsertLokasi() {
        try{
            int i=conn.createStatement().executeUpdate("delete from r_item_lokasi where kode_item='"+sKodeBarang+"' and kode_lokasi='"+txtLokasi.getText()+"'; " +
                    "insert into r_item_lokasi(kode_item, kode_lokasi) values('"+sKodeBarang+"', '"+txtLokasi.getText()+"');");
            udfInitForm();
            if(objForm instanceof FrmSettingHargaJual)
                ((FrmSettingHargaJual)objForm).udfFilter(sKodeBarang);
        }catch(SQLException se){
            JOptionPane.showMessageDialog(this, se.getMessage());
        }
    }

}
