/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmLokasi.java
 *
 * Created on 03 Feb 11, 15:14:53
 */

package retail;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author cak-ust
 */
public class FrmLokasi extends javax.swing.JInternalFrame {
    private Connection conn;
    private String sOldKode="";
    TableColumnModel colModel;

    /** Creates new form FrmLokasi */
    public FrmLokasi() {
        initComponents();
        colModel=tblLokasi.getColumnModel();
        tblLokasi.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {
                int iRow=tblLokasi.getSelectedRow();
                if(iRow>=0){
                    txtKode.setText(tblLokasi.getValueAt(iRow, colModel.getColumnIndex("Kode")).toString());
                    txtNama.setText(tblLokasi.getValueAt(iRow, colModel.getColumnIndex("Lokasi")).toString());
                    txtKeterangan.setText(tblLokasi.getValueAt(iRow, colModel.getColumnIndex("Keterangan")).toString());
                    sOldKode=txtKode.getText();
                }else{
                    sOldKode="";
                    txtKode.setText("");
                    txtNama.setText("");
                    txtKeterangan.setText("");
                }

            }
        });
    }

    private void udfNew(){
        sOldKode="";
        txtKode.setText("");
        txtNama.setText("");
        txtKeterangan.setText("");
    }
    
    private void udfLoadLokasi(){
        try{
            int iSel=0;
            ((DefaultTableModel)tblLokasi.getModel()).setNumRows(0);
            ResultSet rs=conn.createStatement().executeQuery(
                    "select kode_lokasi, coalesce(nama_lokasi,'') as nama_lokasi, coalesce(keterangan,'') as keterangan " +
                    "from r_lokasi " +
                    "order by kode_lokasi");
            while(rs.next()){
                ((DefaultTableModel)tblLokasi.getModel()).addRow(new Object[]{
                    rs.getString("kode_lokasi"),
                    rs.getString("nama_lokasi"),
                    rs.getString("keterangan")
                });
                if(sOldKode.equalsIgnoreCase(txtKode.getText()))
                    iSel=((DefaultTableModel)tblLokasi.getModel()).getRowCount()-1;

                tblLokasi.setRowSelectionInterval(iSel, iSel);
            }
            rs.close();

        }catch(SQLException se){
            JOptionPane.showMessageDialog(this, se.getMessage());
        }
    }

    public void setConn(Connection con){
        this.conn=con;
    }

    private void udfSave(){
        try{
            String sUpd="";
            if(sOldKode.equalsIgnoreCase("")){
                sUpd="insert into r_lokasi(kode_lokasi, nama_lokasi, keterangan) values('"+txtKode.getText()+"', '"+txtNama.getText()+"', '"+txtKeterangan.getText()+"')";
            }else{
                sUpd="update r_lokasi set kode_lokasi='"+txtKode.getText()+"', " +
                        "nama_lokasi='"+txtNama.getText()+"', " +
                        "keterangan='"+txtKeterangan.getText()+"' " +
                        "where kode_lokasi='"+sOldKode+"'";
            }
            sOldKode=txtKode.getText();
            int i=conn.createStatement().executeUpdate(sUpd);
            udfLoadLokasi();
        }catch(SQLException se){
            JOptionPane.showMessageDialog(this, se.getMessage());
        }
    }

    private void udfInitForm(){
        udfLoadLokasi();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLokasi = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtKeterangan = new javax.swing.JTextField();
        txtKode = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        setClosable(true);
        setTitle("Lokasi");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblLokasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Lokasi", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLokasi.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblLokasi.setAutoscrolls(false);
        tblLokasi.setName("tblLokasi"); // NOI18N
        tblLokasi.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblLokasi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 450, 200));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Loaski");
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 70, 20));

        jLabel2.setText("Kode");
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 20));

        jLabel3.setText("Keterangan");
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, 20));

        txtKeterangan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtKeterangan.setName("txtKeterangan"); // NOI18N
        jPanel1.add(txtKeterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 350, 20));

        txtKode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtKode.setName("txtKode"); // NOI18N
        jPanel1.add(txtKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 100, 20));

        txtNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNama.setName("txtNama"); // NOI18N
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 45, 350, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 100));

        btnNew.setText("Baru");
        btnNew.setName("btnNew"); // NOI18N
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        getContentPane().add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 80, 30));

        btnBatal.setText("Batal");
        btnBatal.setName("btnBatal"); // NOI18N
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 70, 30));

        btnSimpan.setText("Simpan");
        btnSimpan.setName("btnSimpan"); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        udfSave();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        udfInitForm();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        udfNew();
        txtKode.requestFocusInWindow();
    }//GEN-LAST:event_btnNewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLokasi;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables

}
