/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmReportPenjualan.java
 *
 * Created on Jul 11, 2009, 12:26:46 PM
 */

package retail;

import java.awt.Cursor;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import retail.main.GeneralFunction;

/**
 *
 * @author ustadho
 */
public class FrmRptPenjualan extends javax.swing.JInternalFrame {
    private Connection conn;
    private GeneralFunction fn=new GeneralFunction();

    /** Creates new form FrmReportPenjualan */
    public FrmRptPenjualan() {
        initComponents();
        jList1.setSelectedIndex(0);
        jXDatePicker1.setFormats("dd/MM/yyyy");
        jXDatePicker2.setFormats("dd/MM/yyyy");
    }

    public void setConn(Connection con){
        this.conn=con;
        fn.setConn(conn);
    }

    private void udfPreviewSales(){
        HashMap reportParam = new HashMap();
        JasperReport jasperReport = null;
        try {
            reportParam.put("corporate", MainForm.sNamaUsaha);
            reportParam.put("alamat", MainForm.sAlamat);
            reportParam.put("telp", MainForm.sTelp);
            reportParam.put("tanggal1", new SimpleDateFormat("yyyy-MM-dd").format(jXDatePicker1.getDate()));
            reportParam.put("tanggal2", new SimpleDateFormat("yyyy-MM-dd").format(jXDatePicker2.getDate()));
            reportParam.put("jenis", jComboBox1.getSelectedIndex()==0? "": jComboBox1.getSelectedItem().toString().subSequence(0, 1));
            reportParam.put("kategori", cmbKategori.getSelectedIndex()==0? "": cmbKategori.getSelectedItem().toString());
            reportParam.put("kode_cust", txtCust.getText());

            setCursor(new Cursor(Cursor.WAIT_CURSOR));
            String sReport="";
            switch(jList1.getSelectedIndex()){
                case 0:{sReport="sales_rekap"; break;}
                case 1:{sReport="Sales_Detail2"; break;}
                case 2:{sReport="Sales_PerCustSum"; break;}
                case 3:{sReport="Sales_PerJenisCustSum"; break;}
                case 4:{sReport="Sales_PerCustDet"; break;}
                case 5:{sReport="Sales_ByItem"; break;}
                case 6:{sReport="Sales_ByItemDetail"; break;}
                case 7:{sReport="sales_rekap_per_tanggal"; break;}
                case 8:{sReport="sales_revenue"; break;}

            }
            jasperReport = (JasperReport) JRLoader.loadObject(getClass().getResourceAsStream("Reports/"+sReport+".jasper"));

            if(sReport.length()==0) {
                setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                return;
            }
            JasperPrint print = JasperFillManager.fillReport(jasperReport, reportParam, conn);
            print.setOrientation(jasperReport.getOrientation());
            if (print.getPages().isEmpty()) {
                setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
                return;
            }
            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            JasperViewer.viewReport(print, false);

        } catch (JRException ex) {
            setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
            System.out.println(ex.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmbKategori = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtCust = new javax.swing.JTextField();
        lblCust = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setClosable(true);
        setTitle("Laporan Penjualan");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Jenis");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 50, 20));

        jLabel2.setText("Dari");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 20));
        jPanel1.add(jXDatePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 170, -1));
        jPanel1.add(jXDatePicker2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 170, -1));

        jLabel3.setText("Sampai");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semua", "Tunai", "Kredit" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 90, -1));

        jLabel4.setText("Pelanggan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 70, 20));

        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 170, -1));

        jLabel5.setText("Kategori");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, 20));

        txtCust.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCust.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustKeyReleased(evt);
            }
        });
        jPanel1.add(txtCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 50, 20));

        lblCust.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 120, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 280, 230));

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 75, 30));

        jButton2.setText("Preview");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 87, 30));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "1.  Ringkasan Faktur Penjualan", "2.  Rincian Faktur Penjualan", "3.  Ringkasan Faktur Penjualan per Pelanggan", "4.  Ringkasan Faktur Penjualan per Jenis Transaksi/Pelanggan", "5.  Rincian Faktur Penjualan per Pelanggan", "6.  Ringkasan Penjualan per Barang", "7.  Rincian Penjualan per Barang", "8.  Ringkasan Total Penjualan per Tanggal", "9.  Selisih Harga Pokok <> Penjualan" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        udfPreviewSales();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        cmbKategori.removeAllItems();
        cmbKategori.addItem("All");
        try{
            ResultSet rs=conn.createStatement().executeQuery("select coalesce(kategori,'') from r_item_kategori order by 1");
            while(rs.next()){
                cmbKategori.addItem(rs.getString(1));
            }
            rs.close();
        }catch(SQLException se){
            JOptionPane.showMessageDialog(this, se.getMessage());
        }
    }//GEN-LAST:event_formInternalFrameOpened


    private void txtCustKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustKeyReleased
        fn.lookup(evt, new Object[]{lblCust} , "select kode_cust, coalesce(nama,'') as nama from r_customer where " +
                "kode_cust||coalesce(nama,'') ilike '%"+txtCust.getText()+"%' order by 2",
                txtCust.getWidth()+lblCust.getWidth()+30, 150);
    }//GEN-LAST:event_txtCustKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbKategori;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private javax.swing.JLabel lblCust;
    private javax.swing.JTextField txtCust;
    // End of variables declaration//GEN-END:variables

}
