package akuntansi.Reports;

/*
 * Generated by JasperReports - 6/11/10 4:21 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import net.sf.jasperreports.engine.*;
import java.util.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class NeracaLajur_1276248079737_14464 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_tahun = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_unit = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_sUnit = null;
    private JRFillParameter parameter_tanggal1 = null;
    private JRFillParameter parameter_tanggal2 = null;
    private JRFillParameter parameter_alamat = null;
    private JRFillParameter parameter_nama_koperasi = null;
    private JRFillParameter parameter_telp = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillField field_saldo_debet = null;
    private JRFillField field_neraca_d = null;
    private JRFillField field_rl_d = null;
    private JRFillField field_acc_no = null;
    private JRFillField field_group_id = null;
    private JRFillField field_rl_k = null;
    private JRFillField field_acc_name = null;
    private JRFillField field_neraca_k = null;
    private JRFillField field_saldo_kredit = null;
    private JRFillField field_penyesuaian_kredit = null;
    private JRFillField field_penyesuaian_debet = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_saldo_adj_debet = null;
    private JRFillVariable variable_saldo_adj_kredit = null;
    private JRFillVariable variable_neraca_debet = null;
    private JRFillVariable variable_neraca_kredit = null;
    private JRFillVariable variable_tot_saldo_d = null;
    private JRFillVariable variable_tot_saldo_k = null;
    private JRFillVariable variable_tot_penyesuaian_d = null;
    private JRFillVariable variable_tot_penyesuaian_k = null;
    private JRFillVariable variable_tot_disesuaikan_d = null;
    private JRFillVariable variable_tot_disesuaikan_k = null;
    private JRFillVariable variable_tot_rl_d = null;
    private JRFillVariable variable_tot_rl_k = null;
    private JRFillVariable variable_tot_neraca_d = null;
    private JRFillVariable variable_tot_neraca_k = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_tahun = (JRFillParameter)pm.get("tahun");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_unit = (JRFillParameter)pm.get("unit");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_sUnit = (JRFillParameter)pm.get("sUnit");
        parameter_tanggal1 = (JRFillParameter)pm.get("tanggal1");
        parameter_tanggal2 = (JRFillParameter)pm.get("tanggal2");
        parameter_alamat = (JRFillParameter)pm.get("alamat");
        parameter_nama_koperasi = (JRFillParameter)pm.get("nama_koperasi");
        parameter_telp = (JRFillParameter)pm.get("telp");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_saldo_debet = (JRFillField)fm.get("saldo_debet");
        field_neraca_d = (JRFillField)fm.get("neraca_d");
        field_rl_d = (JRFillField)fm.get("rl_d");
        field_acc_no = (JRFillField)fm.get("acc_no");
        field_group_id = (JRFillField)fm.get("group_id");
        field_rl_k = (JRFillField)fm.get("rl_k");
        field_acc_name = (JRFillField)fm.get("acc_name");
        field_neraca_k = (JRFillField)fm.get("neraca_k");
        field_saldo_kredit = (JRFillField)fm.get("saldo_kredit");
        field_penyesuaian_kredit = (JRFillField)fm.get("penyesuaian_kredit");
        field_penyesuaian_debet = (JRFillField)fm.get("penyesuaian_debet");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_saldo_adj_debet = (JRFillVariable)vm.get("saldo_adj_debet");
        variable_saldo_adj_kredit = (JRFillVariable)vm.get("saldo_adj_kredit");
        variable_neraca_debet = (JRFillVariable)vm.get("neraca_debet");
        variable_neraca_kredit = (JRFillVariable)vm.get("neraca_kredit");
        variable_tot_saldo_d = (JRFillVariable)vm.get("tot_saldo_d");
        variable_tot_saldo_k = (JRFillVariable)vm.get("tot_saldo_k");
        variable_tot_penyesuaian_d = (JRFillVariable)vm.get("tot_penyesuaian_d");
        variable_tot_penyesuaian_k = (JRFillVariable)vm.get("tot_penyesuaian_k");
        variable_tot_disesuaikan_d = (JRFillVariable)vm.get("tot_disesuaikan_d");
        variable_tot_disesuaikan_k = (JRFillVariable)vm.get("tot_disesuaikan_k");
        variable_tot_rl_d = (JRFillVariable)vm.get("tot_rl_d");
        variable_tot_rl_k = (JRFillVariable)vm.get("tot_rl_k");
        variable_tot_neraca_d = (JRFillVariable)vm.get("tot_neraca_d");
        variable_tot_neraca_k = (JRFillVariable)vm.get("tot_neraca_k");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("Koperasi karyawan Siloam Hospitals Surabaya");//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.String)("Jl. Raya Gubeng 70");//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.String)("031-503 1333");//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.String)("2007");//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.String)("2007-01-01");//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.String)("2010-01-01");//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.String)("");//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.Double)(new java.lang.Double((((java.lang.Double)field_saldo_debet.getValue())).doubleValue()+(((java.lang.Double)field_penyesuaian_debet.getValue())).doubleValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.Double)(new java.lang.Double(((java.lang.Double)field_saldo_kredit.getValue()).doubleValue()+((java.lang.Double)field_penyesuaian_kredit.getValue()).doubleValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.Double)(((java.lang.String)field_group_id.getValue()).equalsIgnoreCase("1")||((java.lang.String)field_group_id.getValue()).equalsIgnoreCase("2")||((java.lang.String)field_group_id.getValue()).equalsIgnoreCase("3") ? //$JR_EXPR_ID=17$
(new java.lang.Double(((java.lang.String)field_group_id.getValue()).equalsIgnoreCase("1")?(((java.lang.Double)field_penyesuaian_debet.getValue()).doubleValue()-((java.lang.Double)field_penyesuaian_kredit.getValue()).doubleValue()) : (0))//$JR_EXPR_ID=17$
): new java.lang.Double(0));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.Double)(((java.lang.String)field_group_id.getValue()).equalsIgnoreCase("1")||((java.lang.String)field_group_id.getValue()).equalsIgnoreCase("2")||((java.lang.String)field_group_id.getValue()).equalsIgnoreCase("3")? //$JR_EXPR_ID=18$
new java.lang.Double((((java.lang.String)field_group_id.getValue()).equalsIgnoreCase("2")||((java.lang.String)field_group_id.getValue()).equalsIgnoreCase("3")||((java.lang.String)field_group_id.getValue()).equalsIgnoreCase("5") ? //$JR_EXPR_ID=18$
(((java.lang.Double)field_penyesuaian_kredit.getValue()).doubleValue()-((java.lang.Double)field_penyesuaian_debet.getValue()).doubleValue()) : (0))//$JR_EXPR_ID=18$
): new java.lang.Double(0));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_saldo_debet.getValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_saldo_kredit.getValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_penyesuaian_debet.getValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_penyesuaian_kredit.getValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_saldo_adj_debet.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_saldo_adj_kredit.getValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_rl_d.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_rl_k.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_neraca_d.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_neraca_k.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_nama_koperasi.getValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_alamat.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_telp.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.String)("Neraca Lajur");//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)("Per tanggal : "+((java.lang.String)parameter_tanggal1.getValue()).substring( 8,10)+((java.lang.String)parameter_tanggal1.getValue()).substring( 4, 8 )+((java.lang.String)parameter_tanggal1.getValue()).substring( 0, 4 )+//$JR_EXPR_ID=33$
" s/d : "+((java.lang.String)parameter_tanggal2.getValue()).substring( 8,10)+((java.lang.String)parameter_tanggal2.getValue()).substring( 4, 8 )+((java.lang.String)parameter_tanggal2.getValue()).substring( 0, 4 ));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.String)("Unit : "+((java.lang.String)parameter_sUnit.getValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.lang.String)(((java.lang.String)field_acc_no.getValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_saldo_debet.getValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.String)(((java.lang.String)field_acc_name.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_saldo_kredit.getValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_penyesuaian_debet.getValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_penyesuaian_kredit.getValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_saldo_adj_debet.getValue()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_saldo_adj_kredit.getValue()));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_rl_d.getValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_rl_k.getValue()));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_neraca_d.getValue()));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_neraca_k.getValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.lang.String)("Page " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()) + " of ");//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()) + "");//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_saldo_d.getValue()));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_saldo_k.getValue()));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_penyesuaian_d.getValue()));//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_penyesuaian_k.getValue()));//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_disesuaikan_d.getValue()));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_disesuaikan_k.getValue()));//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_rl_d.getValue()));//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_rl_k.getValue()));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_neraca_d.getValue()));//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_neraca_k.getValue()));//$JR_EXPR_ID=58$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("Koperasi karyawan Siloam Hospitals Surabaya");//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.String)("Jl. Raya Gubeng 70");//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.String)("031-503 1333");//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.String)("2007");//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.String)("2007-01-01");//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.String)("2010-01-01");//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.String)("");//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.Double)(new java.lang.Double((((java.lang.Double)field_saldo_debet.getOldValue())).doubleValue()+(((java.lang.Double)field_penyesuaian_debet.getOldValue())).doubleValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.Double)(new java.lang.Double(((java.lang.Double)field_saldo_kredit.getOldValue()).doubleValue()+((java.lang.Double)field_penyesuaian_kredit.getOldValue()).doubleValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.Double)(((java.lang.String)field_group_id.getOldValue()).equalsIgnoreCase("1")||((java.lang.String)field_group_id.getOldValue()).equalsIgnoreCase("2")||((java.lang.String)field_group_id.getOldValue()).equalsIgnoreCase("3") ? //$JR_EXPR_ID=17$
(new java.lang.Double(((java.lang.String)field_group_id.getOldValue()).equalsIgnoreCase("1")?(((java.lang.Double)field_penyesuaian_debet.getOldValue()).doubleValue()-((java.lang.Double)field_penyesuaian_kredit.getOldValue()).doubleValue()) : (0))//$JR_EXPR_ID=17$
): new java.lang.Double(0));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.Double)(((java.lang.String)field_group_id.getOldValue()).equalsIgnoreCase("1")||((java.lang.String)field_group_id.getOldValue()).equalsIgnoreCase("2")||((java.lang.String)field_group_id.getOldValue()).equalsIgnoreCase("3")? //$JR_EXPR_ID=18$
new java.lang.Double((((java.lang.String)field_group_id.getOldValue()).equalsIgnoreCase("2")||((java.lang.String)field_group_id.getOldValue()).equalsIgnoreCase("3")||((java.lang.String)field_group_id.getOldValue()).equalsIgnoreCase("5") ? //$JR_EXPR_ID=18$
(((java.lang.Double)field_penyesuaian_kredit.getOldValue()).doubleValue()-((java.lang.Double)field_penyesuaian_debet.getOldValue()).doubleValue()) : (0))//$JR_EXPR_ID=18$
): new java.lang.Double(0));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_saldo_debet.getOldValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_saldo_kredit.getOldValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_penyesuaian_debet.getOldValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_penyesuaian_kredit.getOldValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_saldo_adj_debet.getOldValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_saldo_adj_kredit.getOldValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_rl_d.getOldValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_rl_k.getOldValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_neraca_d.getOldValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_neraca_k.getOldValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_nama_koperasi.getValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_alamat.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_telp.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.String)("Neraca Lajur");//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)("Per tanggal : "+((java.lang.String)parameter_tanggal1.getValue()).substring( 8,10)+((java.lang.String)parameter_tanggal1.getValue()).substring( 4, 8 )+((java.lang.String)parameter_tanggal1.getValue()).substring( 0, 4 )+//$JR_EXPR_ID=33$
" s/d : "+((java.lang.String)parameter_tanggal2.getValue()).substring( 8,10)+((java.lang.String)parameter_tanggal2.getValue()).substring( 4, 8 )+((java.lang.String)parameter_tanggal2.getValue()).substring( 0, 4 ));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.String)("Unit : "+((java.lang.String)parameter_sUnit.getValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.lang.String)(((java.lang.String)field_acc_no.getOldValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_saldo_debet.getOldValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.String)(((java.lang.String)field_acc_name.getOldValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_saldo_kredit.getOldValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_penyesuaian_debet.getOldValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_penyesuaian_kredit.getOldValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_saldo_adj_debet.getOldValue()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_saldo_adj_kredit.getOldValue()));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_rl_d.getOldValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_rl_k.getOldValue()));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_neraca_d.getOldValue()));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_neraca_k.getOldValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.lang.String)("Page " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()) + " of ");//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()) + "");//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_saldo_d.getOldValue()));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_saldo_k.getOldValue()));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_penyesuaian_d.getOldValue()));//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_penyesuaian_k.getOldValue()));//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_disesuaikan_d.getOldValue()));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_disesuaikan_k.getOldValue()));//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_rl_d.getOldValue()));//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_rl_k.getOldValue()));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_neraca_d.getOldValue()));//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_neraca_k.getOldValue()));//$JR_EXPR_ID=58$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("Koperasi karyawan Siloam Hospitals Surabaya");//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.String)("Jl. Raya Gubeng 70");//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.String)("031-503 1333");//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.String)("2007");//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.String)("2007-01-01");//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.String)("2010-01-01");//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.String)("");//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.lang.Double)(new java.lang.Double((((java.lang.Double)field_saldo_debet.getValue())).doubleValue()+(((java.lang.Double)field_penyesuaian_debet.getValue())).doubleValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.lang.Double)(new java.lang.Double(((java.lang.Double)field_saldo_kredit.getValue()).doubleValue()+((java.lang.Double)field_penyesuaian_kredit.getValue()).doubleValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.Double)(((java.lang.String)field_group_id.getValue()).equalsIgnoreCase("1")||((java.lang.String)field_group_id.getValue()).equalsIgnoreCase("2")||((java.lang.String)field_group_id.getValue()).equalsIgnoreCase("3") ? //$JR_EXPR_ID=17$
(new java.lang.Double(((java.lang.String)field_group_id.getValue()).equalsIgnoreCase("1")?(((java.lang.Double)field_penyesuaian_debet.getValue()).doubleValue()-((java.lang.Double)field_penyesuaian_kredit.getValue()).doubleValue()) : (0))//$JR_EXPR_ID=17$
): new java.lang.Double(0));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.Double)(((java.lang.String)field_group_id.getValue()).equalsIgnoreCase("1")||((java.lang.String)field_group_id.getValue()).equalsIgnoreCase("2")||((java.lang.String)field_group_id.getValue()).equalsIgnoreCase("3")? //$JR_EXPR_ID=18$
new java.lang.Double((((java.lang.String)field_group_id.getValue()).equalsIgnoreCase("2")||((java.lang.String)field_group_id.getValue()).equalsIgnoreCase("3")||((java.lang.String)field_group_id.getValue()).equalsIgnoreCase("5") ? //$JR_EXPR_ID=18$
(((java.lang.Double)field_penyesuaian_kredit.getValue()).doubleValue()-((java.lang.Double)field_penyesuaian_debet.getValue()).doubleValue()) : (0))//$JR_EXPR_ID=18$
): new java.lang.Double(0));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_saldo_debet.getValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_saldo_kredit.getValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_penyesuaian_debet.getValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_penyesuaian_kredit.getValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_saldo_adj_debet.getEstimatedValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_saldo_adj_kredit.getEstimatedValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_rl_d.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_rl_k.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_neraca_d.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_neraca_k.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_nama_koperasi.getValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_alamat.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_telp.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.String)("Neraca Lajur");//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.String)("Per tanggal : "+((java.lang.String)parameter_tanggal1.getValue()).substring( 8,10)+((java.lang.String)parameter_tanggal1.getValue()).substring( 4, 8 )+((java.lang.String)parameter_tanggal1.getValue()).substring( 0, 4 )+//$JR_EXPR_ID=33$
" s/d : "+((java.lang.String)parameter_tanggal2.getValue()).substring( 8,10)+((java.lang.String)parameter_tanggal2.getValue()).substring( 4, 8 )+((java.lang.String)parameter_tanggal2.getValue()).substring( 0, 4 ));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.String)("Unit : "+((java.lang.String)parameter_sUnit.getValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.lang.String)(((java.lang.String)field_acc_no.getValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_saldo_debet.getValue()));//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.String)(((java.lang.String)field_acc_name.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_saldo_kredit.getValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_penyesuaian_debet.getValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_penyesuaian_kredit.getValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_saldo_adj_debet.getEstimatedValue()));//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_saldo_adj_kredit.getEstimatedValue()));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_rl_d.getValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_rl_k.getValue()));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_neraca_d.getValue()));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.lang.Double)(((java.lang.Double)field_neraca_k.getValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.lang.String)("Page " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()) + " of ");//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)("" + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()) + "");//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_saldo_d.getEstimatedValue()));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_saldo_k.getEstimatedValue()));//$JR_EXPR_ID=50$
                break;
            }
            case 51 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_penyesuaian_d.getEstimatedValue()));//$JR_EXPR_ID=51$
                break;
            }
            case 52 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_penyesuaian_k.getEstimatedValue()));//$JR_EXPR_ID=52$
                break;
            }
            case 53 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_disesuaikan_d.getEstimatedValue()));//$JR_EXPR_ID=53$
                break;
            }
            case 54 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_disesuaikan_k.getEstimatedValue()));//$JR_EXPR_ID=54$
                break;
            }
            case 55 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_rl_d.getEstimatedValue()));//$JR_EXPR_ID=55$
                break;
            }
            case 56 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_rl_k.getEstimatedValue()));//$JR_EXPR_ID=56$
                break;
            }
            case 57 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_neraca_d.getEstimatedValue()));//$JR_EXPR_ID=57$
                break;
            }
            case 58 : 
            {
                value = (java.lang.Double)(((java.lang.Double)variable_tot_neraca_k.getEstimatedValue()));//$JR_EXPR_ID=58$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
