/*
 * ListRsbm.java
 *
 * Created on May 27, 2005, 8:18 PM
 */

package akuntansi;

import java.awt.Frame;
import java.sql.*;
//import javax.swing.JRootPane;
/**
 *
 * @author  root
 */
public class ListCH1 extends javax.swing.JFrame {
    static Connection con;
    private ResultSet rs;
    private String sQuery;
    private Object[] oResult;
    private javax.swing.table.DefaultTableModel myModel;
    private javax.swing.JTextField txtCari;
    private javax.swing.JLabel[] lblDes;
    private javax.swing.JTable tbl;
    //private javax.swing.JTextField txtCari;
    private int iPosRow = 0,iRow;
    private int jumlah=0;
    /** Creates new form ListRsbm */
    public ListCH1() {
        initComponents();
        getRootPane().setWindowDecorationStyle(NORMAL);
   }

    public ListCH1(String newQry)  throws SQLException {
        initComponents();
        setSQuery(newQry);
        tblList.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        this.setUndecorated(false);
        this.setState(Frame.NORMAL);

    }
    
    public void setRs(ResultSet newRS)  throws SQLException {
        rs = newRS;
        setMyModel(rs);
    }
    
    
    public ResultSet getRs() {
        return rs;
    }
    
    public void setSQuery(String newQry) throws SQLException{
        sQuery = newQry;        
        Statement st = con.createStatement();
        rs = st.executeQuery(sQuery);
        
        
        setMyModel(rs);
        rs.close();
        st.close();
    }
    
    public String getSQuery(){
        return sQuery;
    }
    
    public void setLblDes(javax.swing.JLabel[] newlbl){
        lblDes = newlbl;
    }

    public void setTable(javax.swing.JTable tabl){
        tbl=tabl;
    }
    
    public void setTxtCari(javax.swing.JTextField newTxt){
        txtCari = newTxt;
    }
    
    public int getJumlahRow(){
        return jumlah;
    }

    public void setIRow(Integer iRow){
        this.iRow=iRow;
    }
    
    
    public void setMyModel(ResultSet newRS)  throws SQLException {
        myModel = new javax.swing.table.DefaultTableModel();
        tblList.setModel(myModel);
            
            for(int i=1;i <= rs.getMetaData().getColumnCount();i++) {
                myModel.addColumn(rs.getMetaData().getColumnName(i));
            }
        
            jumlah=0;
            while (newRS.next()) {
                Object arObj[] = new Object[newRS.getMetaData().getColumnCount()];
                for(int i=1;i <= newRS.getMetaData().getColumnCount();i++) {
                    if(newRS.getObject(i) != null){
                        arObj[i-1]=newRS.getObject(i);
                    } else {                        
                        arObj[i-1]=new Object();
                    }
                }
                myModel.addRow(arObj);
                jumlah=myModel.getRowCount();
            }
            if (tblList.getRowCount()>0) tblList.setRowSelectionInterval(0,0);
            newRS.close();    
}
    
    public Object[] getOResult() {
        Object[] oSelected =new Object[tblList.getColumnCount()];
        
        if (tblList.getRowCount()>0) {        
            if (iPosRow == 0) {iPosRow =tblList.getSelectedRow();}
            for(int i=1;i <= tblList.getColumnCount();i++) {
                oSelected[i-1] = tblList.getValueAt(iPosRow, i-1);
            }
        }
        oResult = oSelected;
        return oResult;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();

        setAlwaysOnTop(true);
        setIconImages(null);
        setResizable(false);
        setUndecorated(true);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tblList.setBackground(new java.awt.Color(204, 255, 255));
        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblList.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblList.setSelectionBackground(new java.awt.Color(255, 153, 255));
        tblList.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListMouseClicked(evt);
            }
        });
        tblList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tblListFocusLost(evt);
            }
        });
        tblList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblListKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblListKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblList);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
      
    }//GEN-LAST:event_formFocusLost

    private void tblListFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblListFocusLost
//        this.setVisible(false);
    }//GEN-LAST:event_tblListFocusLost

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tblListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListMouseClicked
        //if (evt.getClickCount()==2){
            iPosRow =tblList.getSelectedRow();
            this.setVisible(false);
            txtCari.setText(tblList.getValueAt(iPosRow, 0).toString());                          
            txtCari.requestFocus();
            for (int i=0;i<lblDes.length;i++){
                lblDes[i].setText(tblList.getValueAt(iPosRow, i+1).toString());
            }

            for(int i=1;i < tblList.getColumnCount();i++) {
                tbl.setValueAt(tblList.getValueAt(iPosRow, i),iRow,i);
            }
        //    System.out.println(evt.getClickCount());
        //}
        //System.out.println(evt.getModifiersExText(1));
        //System.out.println(evt.getModifiersExText(2));
        //System.out.println(evt.getModifiersExText(3));
    }//GEN-LAST:event_tblListMouseClicked

    private void tblListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblListKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {                       
          //  getOResult();
            
            iPosRow =tblList.getSelectedRow();
            this.setVisible(false);
            txtCari.setText(tblList.getValueAt(tblList.getSelectedRow(), 0).toString());                            
            txtCari.requestFocus();            
            for (int i=0;i<lblDes.length;i++){
                lblDes[i].setText(tblList.getValueAt(iPosRow, i+1).toString());
            }
            for(int i=1;i < tblList.getColumnCount();i++) {
                tbl.setValueAt(tblList.getValueAt(iPosRow, i),iRow,i);
            }
        }          
        
    }//GEN-LAST:event_tblListKeyPressed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        tblList.requestFocus();
    }//GEN-LAST:event_formFocusGained

    private void tblListKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblListKeyReleased

        
    }//GEN-LAST:event_tblListKeyReleased
    
    public void setColWidth(int ColIndex, int ColWidth) {                        
        tblList.getColumnModel().getColumn(ColIndex).setPreferredWidth(ColWidth);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblList;
    // End of variables declaration//GEN-END:variables

    
    
}
